#!/bin/bash

# (C) Copyright IBM Corporation 2016
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script must be run as root
#
# The only parameter is the name of the user to be added to the mqm group.

tar -xzf mqadv_dev90_linux_x86-64.tar.gz
cd MQServer
./mqlicense.sh -accept
apt-get -y install rpm
rpm -ivh --force-debian *.rpm

/opt/mqm/bin/setmqinst -i -p /opt/mqm
echo '. /opt/mqm/bin/setmqenv -s' >> $HOME/.bashrc
echo 'export AMQ_INHIBIT_O_DIRECT=TRUE' >> $HOME/.bashrc

usermod -a -G mqm $1

