//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mqWebSite.DynamicData.FieldTemplates
{


    public partial class DynamicDataField1_EditField
    {

        protected System.Web.UI.WebControls.TextBox TextBox1;

        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;

        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;

        protected System.Web.DynamicData.DynamicValidator DynamicValidator1;
    }
}
